name: Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - v2

jobs:
  js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x, 26.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --workspaces --if-present

      - name: Typecheck
        run: npm run typecheck --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present

      - name: Test
        run: npm run coverage --workspaces --if-present

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: node${{ matrix.node-version }}
          files: ./packages/js/coverage/clover.xml
          fail_ci_if_error: true

  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.4", "8.5"]

    defaults:
      run:
        working-directory: packages/php

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Test
        run: vendor/bin/phpunit -c phpunit.coverage.dist.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: php${{ matrix.php-version }}
          files: ./packages/php/clover.xml
          fail_ci_if_error: true

      - name: Lint (Pint)
        run: vendor/bin/pint --test

      - name: Static analysis (PHPStan)
        run: vendor/bin/phpstan analyse
